trigger:
  branches:
    include:
      - main

pool:
  name: MiPool   # o usar 'vmImage: "ubuntu-latest"' si preferís el agente hospedado

variables:
  azureSubscription: 'tp05-connection'     # nombre de tu Service Connection
  webAppFrontendQA: 'webapp-QA-2025'       # nombre de tu Web App Frontend QA
  webAppBackendQA: 'BACKEND-QA-2025'       # nombre de tu Web App Backend QA

stages:
  # ===========================
  # STAGE 1: BUILD (CI)
  # ===========================
  - stage: CI
    displayName: "Build & Test CI"
    jobs:

      # ---------- FRONTEND ----------
      - job: BuildFront
        displayName: "Build Frontend (React)"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: "Set Node.js version"

          - script: |
              set -e
              cd frontend

              echo "📦 Installing and building React app..."
              npm install
              npm run build

              echo "🧩 Creating simple Node server to serve the SPA..."
              cat > build/server.js <<'EOF'
              const express = require("express");
              const path = require("path");
              const compression = require("compression");
              const app = express();
              const port = process.env.PORT || 8080;

              app.use(compression());
              app.use(express.static(path.join(__dirname)));

              app.get("*", (_, res) => {
                res.sendFile(path.join(__dirname, "index.html"));
              });

              app.listen(port, () => console.log(`✅ Frontend running on port ${port}`));
              EOF

              echo "🧾 Creating minimal package.json for Azure WebApp runtime..."
              cat > build/package.json <<'EOF'
              {
                "name": "frontend-spa",
                "version": "1.0.0",
                "private": true,
                "scripts": {
                  "start": "node server.js"
                },
                "dependencies": {
                  "compression": "^1.7.4",
                  "express": "^4.18.2"
                }
              }
              EOF

              echo "📦 Installing dependencies for runtime..."
              cd build
              npm install --production
            displayName: "Build React + Add server.js and package.json"

          - task: ArchiveFiles@2
            displayName: "Zip frontend build (with Node server)"
            inputs:
              rootFolderOrFile: 'frontend/build'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)/frontend.zip
            artifact: drop_front
            displayName: "Publish Frontend Artifact"

      # ---------- BACKEND ----------
      - job: BuildBack
        displayName: "Build Backend (Go)"
        steps:
          - task: GoTool@0
            inputs:
              version: '1.22.5'
            displayName: "Use Go 1.22.5"

          - script: |
              cd Golang
              go version
              go mod tidy
              go test ./... -v
              GOOS=linux GOARCH=amd64 go build -o app
            displayName: "Test & Build Backend"

          - task: ArchiveFiles@2
            displayName: "Zip backend binary"
            inputs:
              rootFolderOrFile: 'Golang/app'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)/backend.zip
            artifact: drop_back
            displayName: "Publish Backend Artifact"


  # ===========================
  # STAGE 2: DEPLOY TO QA (CD)
  # ===========================
  - stage: DeployQA
    displayName: "Deploy to QA Environment"
    dependsOn: CI
    condition: succeeded()
    jobs:

      # ---------- DEPLOY FRONTEND ----------
      - deployment: DeployFrontendQA
        displayName: "Deploy Frontend QA"
        environment: 'QA'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop_front

                - task: AzureWebApp@1
                  displayName: "Deploy Frontend to QA Web App"
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    appType: 'webApp'
                    appName: '$(webAppFrontendQA)'
                    package: '$(Pipeline.Workspace)/drop_front/frontend.zip'

      # ---------- DEPLOY BACKEND ----------
      - deployment: DeployBackendQA
        displayName: "Deploy Backend QA"
        environment: 'QA'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop_back

                - task: AzureWebApp@1
                  displayName: "Deploy Backend to QA Web App"
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    appType: 'webApp'
                    appName: '$(webAppBackendQA)'
                    package: '$(Pipeline.Workspace)/drop_back/backend.zip'
